name: Build and Release

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "sbt"

      - name: Install sbt (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
          sudo apt update
          sudo apt install -y sbt

      - name: Install sbt (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install sbt

      - name: Install sbt (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install sbt -y

      - name: Build Fat Jar (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sbt assembly

      - name: Upload Fat Jar
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: jagfx-fat-jar
          path: target/scala-*/*.jar

      - name: Build Distribution
        shell: bash
        run: sbt "Universal/packageBin"

      - name: Upload Distribution
        uses: actions/upload-artifact@v4
        with:
          name: jagfx-${{ matrix.os }}
          path: target/universal/*.zip
